Resolve pub dependencies
```
Resolving dependencies...
Because flutter_tizen depends on flutter_test any which doesn't exist (could not find package flutter_test at https://pub.dev), version solving failed.
Failed to update packages.
Error: Unable to 'pub upgrade' flutter-tizen.
```